services:
  db:
    image: mysql:latest
    restart: always
    container_name: flask_auth_demo_db
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "auth-demo"
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
